extends SceneTree
## Writes src/sim/core/trig_lut.gd: cos and sin for angles 0..512 (of 4096 per turn) as exact float32 bit
## patterns. The sim never calls trig; Kin rebuilds every direction from this octant by symmetry.
## Run on purpose only, then format: godot --headless --path . -s scripts/sim/gen_trig_lut.gd && gdformat src/sim/core

const OUT := "res://src/sim/core/trig_lut.gd"


func _initialize() -> void:
	var cos_f := PackedFloat32Array()
	var sin_f := PackedFloat32Array()
	for i in 513:
		var a := TAU * i / 4096.0
		var c := cos(a)
		var s := sin(a)
		if i == 512:
			s = c  # cos 45° == sin 45° exactly, so the octant mirror is exact.
		cos_f.append(c)
		sin_f.append(s)
	var lines := PackedStringArray()
	lines.append("class_name TrigLut")
	lines.append("extends RefCounted")
	lines.append("## GENERATED by scripts/sim/gen_trig_lut.gd. Do not edit.")
	lines.append("## Little-endian float32 bytes as hex, angles 0..512 of 4096 per turn.")
	lines.append("")
	lines.append(
		"const COS_HEX: Array[String] = [%s]" % _chunks(cos_f.to_byte_array().hex_encode())
	)
	lines.append(
		"const SIN_HEX: Array[String] = [%s]" % _chunks(sin_f.to_byte_array().hex_encode())
	)
	var f := FileAccess.open(OUT, FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")
	f.close()
	print("wrote ", OUT)
	quit(0)


func _chunks(hex: String) -> String:
	var parts := PackedStringArray()
	for i in range(0, hex.length(), 96):
		parts.append('"%s"' % hex.substr(i, 96))
	return ", ".join(parts)
