class_name ScoreSuite
extends RefCounted
## The scorecard's plan and outputs (v0.5.0 SCD), shared by scripts/sims/scorecard.gd (the command) and
## tests/unit/sims/test_scorecard.gd (quick mode, in process). A task is "<policy>:<build>[@<skill>]#<seed>"; each
## plays one ScoreRun. The aggregate is every SCORECARD §2 cell (ScoreCells) written as scorecard.json (keys sorted,
## no wall time) and scorecard.md; wall times go to timings.tsv only.

## Full mode: every policy SCORECARD §3 names that this game can run, both builds where the policy has no build.
const FULL_POLICIES: Array[String] = [
	"idle:blade",
	"idle:gun",
	"novice:blade",
	"novice:gun",
	"competent:blade",
	"competent:gun",
	"competent:blade@novice",
	"competent:gun@novice",
	"competent:blade@expert",
	"competent:gun@expert",
	"competent+t:blade",
	"competent+t:gun",
	"element:blade",
	"ordnance:blade",
	"guard:blade",
	"element:gun",
	"ordnance:gun",
	"guard:gun",
	"exploit:salvage:blade",
	"exploit:salvage:gun",
	"exploit:chain:blade",
	"exploit:chain:gun",
]
## Quick mode (CI): one of each kind, so every cell is produced.
const QUICK_POLICIES: Array[String] = [
	"idle:blade",
	"novice:gun",
	"competent:blade",
	"competent:gun",
	"competent:blade@expert",
	"competent+t:blade",
	"element:blade",
	"ordnance:gun",
	"guard:blade",
	"exploit:salvage:blade",
	"exploit:chain:gun",
]
## Run seeds: seed k (1-based) plays run seed SEED_BASE + k.
const SEED_BASE := 20261000
const QUICK_FLOORS := 1
const QUICK_FLOOR_TICKS := 1800


static func tasks(policies: Array, seeds: Array) -> PackedStringArray:
	var out := PackedStringArray()
	for s: int in seeds:
		for p: String in policies:
			out.append("%s#%d" % [p, s])
	return out


## A task's parts: {policy, build, skill, seed}.
static func parse(task: String) -> Dictionary:
	var at_seed := task.split("#")
	var head := at_seed[0]
	var skill := "average"
	if head.contains("@"):
		skill = head.get_slice("@", 1)
		head = head.get_slice("@", 0)
	var cut := head.rfind(":")
	return {
		"policy": head.substr(0, cut),
		"build": head.substr(cut + 1),
		"skill": skill,
		"seed": int(at_seed[1]),
	}


## Plays one task; returns its record.
static func play(repo: ContentRepository, task: String, floors: int, floor_ticks: int) -> Dictionary:
	var t := parse(task)
	var rec := ScoreRun.play(
		repo,
		SEED_BASE + int(t["seed"]),
		t["policy"],
		StringName(t["build"]),
		t["skill"],
		floors,
		floor_ticks
	)
	rec["task"] = task
	rec["seed_index"] = int(t["seed"])
	return rec


## The stress tags of every enemy kind: {kind name: [tags]}.
static func stress_tags(repo: ContentRepository) -> Dictionary:
	var out := {}
	for def: EnemyDefinition in repo.all_of(&"enemies"):
		var t := ContentCompiler.compile_enemy(def)
		var tags: Array = []
		for s in def.stress_tags:
			tags.append(String(s))
		out[ScoreRun.kind_name(t.kind)] = tags
	return out


## The whole document: config, cells and the run index.
static func document(
	records: Array,
	config: Dictionary,
	bench: Dictionary,
	bench_note: String,
	repo: ContentRepository
) -> Dictionary:
	var sorted := records.duplicate()
	sorted.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return a["task"] < b["task"])
	var index: Array = []
	for r: Dictionary in sorted:
		index.append(
			{
				"task": r["task"],
				"result": r["result"],
				"floor_reached": r["floor_reached"],
				"run_ticks": r["run_ticks"],
			}
		)
	return {
		"schema": "scorecard.v1",
		"config": config,
		"cells": ScoreCells.build(sorted, bench, bench_note, stress_tags(repo)),
		"runs": index,
	}


static func write_json(path: String, doc: Variant) -> void:
	DirAccess.make_dir_recursive_absolute(path.get_base_dir())
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string(JSON.stringify(doc, "\t", true) + "\n")
	f.close()


static func read_json(path: String) -> Variant:
	if not FileAccess.file_exists(path):
		return null
	return JSON.parse_string(FileAccess.get_file_as_string(path))


## A task's file name under runs/.
static func file_of(task: String) -> String:
	return task.replace(":", "_").replace("#", "_s").replace("@", "_at_").replace("+", "_plus") + ".json"


# --- The readable table ----------------------------------------------------------------------------------------
static func markdown(doc: Dictionary) -> String:
	var c: Dictionary = doc["config"]
	var lines := PackedStringArray()
	lines.append("# Scorecard %s (%s mode)" % [c["sha"], c["mode"]])
	lines.append("")
	lines.append("Command: `%s`" % c["command"])
	lines.append("")
	lines.append(
		(
			"Seeds %s, %d policies, %d runs, floors %d, floor limit %d ticks. Generated by "
			% [c["seeds"], (c["policies"] as Array).size(), (doc["runs"] as Array).size(), c["floors"], c["floor_ticks"]]
			+ "scripts/sims/scorecard.gd; bands from docs/balance/SCORECARD.md §2."
		)
	)
	lines.append("")
	lines.append("| Cell | Band | Status | Headline |")
	lines.append("|---|---|---|---|")
	for id: String in ScoreCells.IDS:
		var cell: Dictionary = doc["cells"][id]
		lines.append(
			"| %s | %s | %s | %s |" % [id, cell["band"], cell["status"], headline(id, cell)]
		)
	lines.append("")
	for id: String in ScoreCells.IDS:
		var cell: Dictionary = doc["cells"][id]
		lines.append("## %s" % id)
		lines.append("")
		lines.append("%s" % cell["note"])
		lines.append("")
		lines.append("```json")
		var text := JSON.stringify(cell["value"], "  ", true)
		var rows := text.split("\n")
		if rows.size() > 400:
			text = "\n".join(rows.slice(0, 400)) + "\n... (%d more lines in scorecard.json)" % (rows.size() - 400)
		lines.append(text)
		lines.append("```")
		lines.append("")
	lines.append("## Runs")
	lines.append("")
	lines.append("| Task | Result | Floor | Minutes |")
	lines.append("|---|---|---|---|")
	for r: Dictionary in doc["runs"]:
		lines.append(
			"| %s | %s | %d | %.2f |"
			% [r["task"], r["result"], int(r["floor_reached"]), int(r["run_ticks"]) / 3600.0]
		)
	return "\n".join(lines) + "\n"


## One line per cell for the table.
static func headline(id: String, cell: Dictionary) -> String:
	var v: Variant = cell["value"]
	if not v is Dictionary or (v as Dictionary).is_empty():
		return "—"
	var d: Dictionary = v
	match id:
		"M-CAUSE":
			return "%s of %s hits readable" % [str(d.get("readable_share", "—")), str(d.get("damage"))]
		"M-LIMIT":
			return "%s LIMIT events over %s runs %s" % [d["total"], d["runs"], str(d["by_effect"])]
		"M-GAP":
			return "best %s; gaps %s" % [d["best"], _short(d["gap_to_best"])]
		"M-WIN":
			return "competent floor-1 deaths %s" % _rate(d["competent_floor1_death"])
		"M-ENGINE":
			return _rate(d)
		"M-DROUGHT":
			return "longest per run: %s" % _dist(d["longest_per_run"])
		"M-PICK":
			return "picked >= 90 %% everywhere: %s" % str(d["picked_90pct_everywhere"])
		"M-DEAD":
			var b: Dictionary = d["win_rate_by_build"]
			return "Blade %s, Gun %s" % [_rate(b["blade"]), _rate(b["gun"])]
		"M-TTK":
			return "%d build/floor/kind rows" % d.size()
		"M-ENC":
			return "floor 1 bouts %s s" % _dist(d["1"]["bouts_s"])
		"M-FLOOR":
			return "all floors %s min; budget used up %s" % [_dist(d["all"]), d["explore_budget_used_up"]]
		"M-RUN":
			return "full runs %s min" % _dist(d["full_runs"])
		"M-THREAT":
			return (
				"T0 win %s, T1 win %s; floor-1 clear T0 %s, T1 %s"
				% [
					_rate(d["t0_win"]),
					_rate(d["t1_win"]),
					_rate(d["t0_floor1_clear"]),
					_rate(d["t1_floor1_clear"])
				]
			)
		"M-CAP":
			return _short(d)
		"M-STRESS":
			return "untagged: %s" % str(d["untagged_archetypes"])
		"M-HAZARD":
			var parts := PackedStringArray()
			for f: String in d:
				parts.append("floor %s %s pp" % [f, str(d[f]["spread_pp"])])
			return ", ".join(parts)
		"M-BENCH":
			return _short(d)
		"M-MORT":
			return "%d archetypes" % d.size()
		"M-POWER":
			return "%d archetypes" % d.size()
		"M-SYNERGY":
			return "synergy share per floor %s" % _dist(d["synergy_share_per_floor"])
		"M-LOOP":
			return (
				"%d salvage trades (%s spent, %s back), %d loops; chain watchdog %s"
				% [
					int(d["salvage_trades"]),
					str(d["salvage_spent"]),
					str(d["salvage_returned"]),
					(d["salvage_loops"] as Array).size(),
					str(d["chain_watchdog_limits"])
				]
			)
		"M-DIVERGE":
			return "first divergence g %s; never %s" % [_dist(d["all"]), d["never_diverged"]]
		"M-GENERALIST":
			return (
				"competent %s vs best %s %s"
				% [_rate(d["competent"]), d["best_specialist"], _rate(d["best"])]
			)
	return "—"


static func _rate(w: Dictionary) -> String:
	if int(w.get("n", 0)) == 0:
		return "n=0"
	return "%d/%d = %.3f [%.3f, %.3f]" % [w["wins"], w["n"], w["rate"], w["lo"], w["hi"]]


static func _dist(d: Dictionary) -> String:
	if int(d.get("n", 0)) == 0:
		return "n=0"
	return "median %s (p10 %s, p90 %s, max %s, n %d)" % [d["median"], d["p10"], d["p90"], d["max"], d["n"]]


static func _short(v: Variant) -> String:
	var s := JSON.stringify(v, "", true)
	return s if s.length() <= 160 else s.left(157) + "..."
